<?php

return [
    'list' => [
        'this forum is shit!',
        'anal',
        'anus',
        'arse',
        'ballsack',
        'balls',
        'bastard',
        'bitch',
        'biatch',
        'bloody',
        'blowjob',
        'blow job',
        'bollock',
        'bollok',
        'boner',
        'bugger',
        'buttplug',
        'clitoris',
        'cock',
        'crap',
        'cunt',
        'damn',
        'dick',
        'dildo',
        'fuck',
        'f u c k',
        'fudgepacker',
        'fudge packer',
        'flange',
        'Goddamn',
        'God damn',
        'jerk',
        'knobend',
        'knob end',
        'labia',
        'penis',
        'poop',
        'prick',
        'pussy',
        'queer',
        'scrotum',
        'sex',
        'shit',
        'slut',
        'smegma',
        'spunk',
        'tosser',
        'turd',
        'twat',
        'vagina',
        'wank',
        'whore',
    ]
];
